"""
bdf_writer.py
=============
MSC Nastran BDF file writer for VAT composite panel aeroelastic analyses.

Supported solution sequences:
  SOL 103 – Normal modes (free vibration)
  SOL 144 – Static aeroelastic trim + divergence
  SOL 145 – Flutter (PK method)

Public API
----------
write_bdf(...)   Write the complete BDF file and return the node dictionary.
"""

import numpy as np


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _spc_code(disp, rot):
    """
    Build the Nastran SPC DOF string from displacement and rotation flags.

    Parameters
    ----------
    disp : list of int  [u1, u2, u3]  – 1 = constrained
    rot  : list of int  [r1, r2, r3]  – 1 = constrained
    """
    dofs = (
        ["1"] * bool(disp[0]) +
        ["2"] * bool(disp[1]) +
        ["3"] * bool(disp[2]) +
        ["4"] * bool(rot[0])  +
        ["5"] * bool(rot[1])  +
        ["6"] * bool(rot[2])
    )
    return "".join(dofs)


def _mat8_line(props):
    """
    Format the MAT8 card using compact Nastran scientific notation
    (e.g. 1.73+11 instead of 1.73e+11).
    """
    parts = ["MAT8     1       "]
    for val in props:
        if isinstance(val, float) and abs(val) >= 1e6:
            base, exp = f"{val:.3e}".split("e")
            base = base.rstrip("0").rstrip(".")
            if "." not in base:
                base += "."
            exp_sign = "+" if int(exp) >= 0 else "-"
            exp_val  = str(abs(int(exp))).lstrip("0") or "0"
            parts.append(f"{base}{exp_sign}{exp_val:<8}"[:8])
        else:
            s = str(val)
            if "." not in s:
                s += "."
            parts.append(f"{s:<8}")
    return "".join(parts).strip()


def _write_list_card(f, card_name, id_list):
    """
    Write a multi-line Nastran list card (AELIST, SET1, FLFACT, …)
    with automatic continuation lines.
    """
    ids         = list(id_list)
    first_chunk = ids[:7]
    rest        = ids[7:]
    f.write(f"{card_name},{','.join(map(str, first_chunk))}\n")
    for i in range(0, len(rest), 8):
        f.write("," + ",".join(map(str, rest[i:i+8])) + "\n")


def _t_ply_fmt(t):
    """
    Format a ply thickness value in compact Nastran notation
    (e.g. 1.000-02 instead of 1.000e-02).
    """
    s          = f"{t:.7e}"
    base, exp_str = s.split("e")
    base       = base.rstrip("0").rstrip(".")
    sign       = "+" if int(exp_str) >= 0 else "-"
    exp_val    = str(abs(int(exp_str))).lstrip("0") or "0"
    return f"{base}{sign}{exp_val}"


# ---------------------------------------------------------------------------
# Executive Control section
# ---------------------------------------------------------------------------

def _write_executive(f, sol):
    f.write("$ MSC.Nastran input file generated by script\n")
    f.write(f"SOL {sol:d}\n")
    f.write("CEND\n")


# ---------------------------------------------------------------------------
# Case Control section
# ---------------------------------------------------------------------------

def _write_case_control(f, sol):
    if sol == 103:
        f.write("TITLE = Modal analysis of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   METHOD = 1\n")
        f.write("   SPC = 2\n")
        f.write("   VECTOR(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")

    elif sol == 144:
        f.write("DIVERG = 50\n")
        f.write("CMETHOD = 50\n")
        f.write("TITLE = SSA of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("AECONFIG = AeroSG2D\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   SPC = 2\n")
        f.write("   DISPLACEMENT(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")
        f.write("   STRESS(SORT1,REAL,VONMISES,BILIN)=ALL\n")
        f.write("TRIM = 1\n")
        f.write("AESYMXZ = Symmetric\n")
        f.write("AESYMXY = Asymmetric\n")
        f.write("AEROF = ALL\n")
        f.write("APRES = ALL\n")

    elif sol == 145:
        f.write("TITLE = Flutter analysis of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("AECONFIG = AeroSG2D\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   METHOD = 1\n")
        f.write("   SPC = 2\n")
        f.write("   VECTOR(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")
        f.write("FMETHOD = 1\n")
        f.write("AESYMXZ = Symmetric\n")
        f.write("AESYMXY = Asymmetric\n")


# ---------------------------------------------------------------------------
# Bulk Data section
# ---------------------------------------------------------------------------

def _write_output_param(f, output_format):
    """Write the PARAM card that selects the output database format."""
    fmt = output_format.lower()
    if fmt == "hdf5":
        f.write("HDF5OUT PRCISION 32     CMPRMTHD LZ4     LEVEL   5\n")
    elif fmt == "xdb":
        f.write("PARAM    POST      0\n")
    elif fmt == "op2":
        f.write("PARAM    POST      1\n")
    else:
        raise ValueError(f"Unknown output_format '{output_format}'. Use 'op2', 'xdb', or 'hdf5'.")


def _write_bulk_params(f, sol):
    """Write miscellaneous PARAM cards required by each solution sequence."""
    f.write("PARAM   PRTMAXIM YES\n")
    if sol in (103, 145):
        # Request 10 eigenvalues starting from the lowest
        f.write("EIGRL    1                       10      0\n")
    if sol in (144, 145):
        f.write("PARAM    WTMASS 1.\n")
        f.write("PARAM    SNORM  20.\n")


def _write_pcomp(f, theta_deg, t_ply, elem_tags):
    """
    Write one PCOMP card per element to represent the spatially varying
    VAT laminate (one property set per element).
    """
    for pcomp_id in [int(e) for e in elem_tags]:
        f.write(f"PCOMP    {pcomp_id:d}\n")
        for angle in theta_deg[:, pcomp_id - 1]:
            t_fmt = _t_ply_fmt(t_ply)
            f.write(f"*        1               {t_fmt:<16}{angle:<14f}  YES\n")
        f.write("*\n")


def _write_grid(f, node_tags, node_coords):
    """Write GRID cards and return a {tag: (x, y, z)} dictionary."""
    nodes = {}
    for i, tag in enumerate(node_tags):
        x, y, z = node_coords[3*i], node_coords[3*i+1], node_coords[3*i+2]
        f.write(f"GRID,{tag:d},,{x:<8.5f},{y:<8.5f},{z:<8.5f}\n")
        nodes[tag] = (x, y, z)
    return nodes


def _write_elements(f, elem_types, elem_tags, elem_node_tags, gmsh):
    """Write CQUAD4 element cards. Raises if a non-quad element is found."""
    for etype, etags, enodes in zip(elem_types, elem_tags, elem_node_tags):
        if gmsh.model.mesh.getElementProperties(etype)[0] == "Quadrilateral 4":
            for eid, i in enumerate(range(0, len(enodes), 4)):
                n1, n2, n3, n4 = enodes[i:i+4]
                pid = etags[eid]
                f.write(f"CQUAD4,{etags[eid]:d},{pid:d},{n1:d},{n2:d},{n3:d},{n4:d},0\n")
        else:
            raise RuntimeError("Unsupported element type: expected Quadrilateral 4.")


def _write_material(f, props):
    """Write the MAT8 orthotropic material card."""
    f.write(_mat8_line(props) + "\n")


def _write_bcs(f, boundary_conditions, nodes, Lx, Ly, tol=1e-6):
    """
    Write SPC cards for each constrained panel edge.

    Side nodes are selected geometrically using a coordinate tolerance.
    """
    f.write("SPCADD   2       1\n")
    spc_id = 1

    side_filter = {
        "left":   lambda x, y, z: abs(x - 0.0) < tol,
        "right":  lambda x, y, z: abs(x - Lx)  < tol,
        "bottom": lambda x, y, z: abs(y - 0.0) < tol,
        "top":    lambda x, y, z: abs(y - Ly)  < tol,
    }

    for side, bc in boundary_conditions.items():
        flt = side_filter.get(side)
        if flt is None:
            continue
        spc_code = _spc_code(bc["disp"], bc["rot"])
        if not spc_code:
            continue  # all DOFs free on this side → skip
        side_nodes = [nid for nid, coords in nodes.items() if flt(*coords)]
        for nid in side_nodes:
            f.write(f"SPC     {spc_id:<8d} {nid:<8d} {spc_code:<8s}\n")


def _write_aero_common(f, Lx, Ly, rho_fluid, Nx, Ny, Nelems, gmsh, p1, p2, p3, p4):
    """
    Write aerodynamic cards shared by SOL 144 and SOL 145:
    AERO, AEROS, PAERO1, CAERO1, SPLINE4, AELIST, SET1.
    """
    f.write("PARAM   AUNITS  1.\n")

    # Retrieve corner coordinates from gmsh model
    x1, y1, z1 = gmsh.model.getValue(0, p1, [])
    x4, y4, z4 = gmsh.model.getValue(0, p4, [])
    x2, y2, z2 = gmsh.model.getValue(0, p2, [])
    x3, y3, z3 = gmsh.model.getValue(0, p3, [])
    x12 = x2 - x1   # root chord
    x43 = x3 - x4   # tip chord

    f.write(f"AERO,0,1.,{Lx:.4f},{rho_fluid:.4f}\n")
    f.write(f"AEROS,0,0,{Lx:.4f},{Ly*2:.4f},{Lx*Ly:.4f}\n")
    f.write("PAERO1  100001\n")
    f.write(f"CAERO1,100001,100001,0,{Ny:d},{Nx:d},,,1\n")
    f.write(f",{x1:.4f},{y1:.4f},{z1:.4f},{x12:.4f},{x4:.4f},{y4:.4f},{z4:.4f},{x43:.4f}\n")
    f.write("SPLINE4,1,100001,1,,1,,IPS,BOTH\n")

    # List of all aero box IDs and structural node IDs for the spline
    _write_list_card(f, "AELIST,1", range(100001, 100001 + Nelems))
    _write_list_card(f, "SET1,1",   range(1, (Nx+1)*(Ny+1) + 1))


def _write_div_cards(f, N_roots, q, alpha_deg):
    """Write trim, divergence, and eigenvalue cards for SOL 144."""
    alpha_rad = np.deg2rad(alpha_deg)

    # Aerodynamic state variables
    labels = ["ANGLEA", "SIDES", "ROLL", "PITCH", "YAW",
              "URDD1",  "URDD2", "URDD3", "URDD4", "URDD5", "URDD6"]
    for i, lbl in enumerate(labels, start=1):
        f.write(f"AESTAT  {i:<8d}{lbl}\n")

    # Trim condition
    f.write(f"TRIM,1,0.,{q:.4f},ANGLEA,{alpha_rad:.7f},SIDES,0.\n")
    f.write(",ROLL,0.,PITCH,0.,YAW,0.,URDD1,0.\n")
    f.write(",URDD2,0.,URDD3,0.,URDD4,0.,URDD5,0.\n")
    f.write(",URDD6,0.\n")

    # Divergence and complex eigenvalue cards
    f.write(f"DIVERG,50,{N_roots:d},0.0\n")
    f.write(f"EIGC,50,CLAN,MAX,,,,{N_roots:d}\n")


def _write_flutter_cards(f, k_freq, V_range, V_plot):
    """Write MKAERO2, FLFACT, and FLUTTER cards for SOL 145 (PK method)."""
    # Build Mach–k table (Mach = 0 for incompressible)
    Mach = np.zeros_like(k_freq)
    MK   = np.empty(2 * len(k_freq))
    MK[0::2] = Mach
    MK[1::2] = k_freq
    MK = MK.reshape(-1, 8)
    for row in MK:
        row_str = ",".join(f"{x:.6f}" for x in row)
        f.write(f"MKAERO2,{row_str}\n")

    # Density, Mach, and velocity FLFACT entries
    f.write("FLFACT  1       1.\n")   # density factor
    f.write("FLFACT  2       0.0\n")  # Mach number

    V_full = np.append(V_range, V_plot)
    _write_list_card(f, "FLFACT,3", [f"{v}" for v in V_full])

    # Flutter solution card (PK method)
    f.write("FLUTTER 1       PK      1       2       3                       .001\n")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_bdf(
    filename, sol,
    node_tags, node_coords,
    elem_types, elem_tags, elem_node_tags,
    theta_deg, t_ply,
    props, boundary_conditions,
    Lx, Ly, Nx, Ny, Nelems,
    output_format,
    gmsh, p1, p2, p3, p4,
    rho_fluid=1.226, q=None, alpha_deg=1.0, N_roots=10,
    k_freq=None, V_range=None, V_plot=-10,
):
    """
    Write a complete MSC Nastran BDF file.

    Parameters
    ----------
    filename : str
        Full path to the output file without extension.
        The file ``<filename>.bdf`` is created (or overwritten).
    sol : int
        Nastran solution sequence (103, 144, or 145).
    node_tags, node_coords : arrays
        Node IDs and coordinates from gmsh.
    elem_types, elem_tags, elem_node_tags : arrays
        Element data from gmsh.
    theta_deg : np.ndarray, shape (N_layers, N_elements)
        Fibre angles in degrees for the VAT laminate.
    t_ply : float
        Ply thickness [m].
    props : list
        Material properties [E1, E2, nu12, G12, G23, G32, rho].
    boundary_conditions : dict
        Per-side BC dictionary (see config.py).
    Lx, Ly : float
        Panel dimensions [m].
    Nx, Ny : int
        Number of elements along each direction.
    Nelems : int
        Total number of elements.
    output_format : str
        Nastran output format: "op2", "xdb", or "hdf5".
    gmsh : module
        Active gmsh module (used to query corner coordinates).
    p1..p4 : int
        gmsh point tags of the four panel corners.
    rho_fluid : float
        Fluid density [kg/m³] (aeroelastic analyses only).
    q : float
        Dynamic pressure at trim [Pa] (SOL 144 only).
    alpha_deg : float
        Trim angle of attack [deg] (SOL 144 only).
    N_roots : int
        Number of divergence eigenvalues requested (SOL 144 only).
    k_freq : np.ndarray
        Reduced frequency array for MKAERO2 (SOL 145 only).
    V_range : np.ndarray
        Velocity sweep array [m/s] (SOL 145 only).
    V_plot : float
        Velocity for eigenvector output (SOL 145 only).

    Returns
    -------
    nodes : dict
        Mapping {node_tag: (x, y, z)}.
    """
    bdf_path = filename + ".bdf"

    with open(bdf_path, "w") as f:
        _write_executive(f, sol)
        _write_case_control(f, sol)

        f.write("BEGIN BULK\n")
        _write_output_param(f, output_format)
        _write_bulk_params(f, sol)

        _write_pcomp(f, theta_deg, t_ply, elem_tags[0])

        nodes = _write_grid(f, node_tags, node_coords)
        _write_elements(f, elem_types, elem_tags, elem_node_tags, gmsh)

        _write_material(f, props)
        _write_bcs(f, boundary_conditions, nodes, Lx, Ly)

        if sol in (144, 145):
            _write_aero_common(f, Lx, Ly, rho_fluid, Nx, Ny, Nelems,
                               gmsh, p1, p2, p3, p4)
        if sol == 144:
            _write_div_cards(f, N_roots, q, alpha_deg)
        elif sol == 145:
            _write_flutter_cards(f, k_freq, V_range, V_plot)

        f.write("ENDDATA\n")

    return nodes