import numpy as np
import utilities
import subprocess
import os
import sys

import gmsh



# WHICH TEST
# if (len(sys.argv) < 2):
#     print("Please specify analysis type")
#     quit()


ANALYSIS = sys.argv[1]

# Solver -- chose one
if ANALYSIS == "FVIB":
    sol, filename = 103, "CurvedPanelFVIB"          # FVIB
elif ANALYSIS == "DIV":
    sol, filename = 144, "CurvedPanelDIV"           # DIV
elif ANALYSIS == "FLT":
    sol, filename = 145, "CurvedPanelFLT"           # FLT
else:
    print("Analysis type not yet implemented. Choose between FVIB, DIV and FLT  ")
    quit()

params = {}

# Lato da vincolare: 'left', 'right', 'top', 'bottom'
side_to_fix = 'bottom'


# ISO PROP
# Material
E = 6.7999998e10
nu = 0.33
G = E/(2*(1+nu))
rho = 2700
params["t"] = 0.002286

props = [E, G, nu, rho]


# === Geometry
Lx = 0.40538
Ly = 0.6096
Nx = 10  # ELEMENTI lungo x
Ny = 40   #  ELEMENTI lungo y
Nelems = Nx*Ny

sweep = np.deg2rad(0)

## AERO
rho_f = 0.4499257085
M = 0

# SAA
alpha = 1
V = 10
q = 0.5*rho_f*V**2
Nroots = 50

# FLT
V_range = np.linspace(1,150,10)
V_plot = -10                    # TODO, add negative velocities if eigenvector are requested


## STRUCTURE
gmsh.initialize()
gmsh.model.add("mesh")

############################################################
# RECTANGULAR WING
############################################################

# p1 = gmsh.model.geo.addPoint(0, 0, 0, 0)
# p2 = gmsh.model.geo.addPoint(Lx, 0, 0, 0)
# p3 = gmsh.model.geo.addPoint(Ly*np.tan(sweep)+Lx, Ly, 0, 0)
# p4 = gmsh.model.geo.addPoint(Ly*np.tan(sweep), Ly, 0, 0)

# C1 = gmsh.model.geo.addLine(p1, p2)
# C2 = gmsh.model.geo.addLine(p2, p3)
# C3 = gmsh.model.geo.addLine(p3, p4)
# C4 = gmsh.model.geo.addLine(p4, p1)

# cl = gmsh.model.geo.addCurveLoop([C1, C2, C3, C4])
# ps = gmsh.model.geo.addPlaneSurface([cl])

# gmsh.model.geo.synchronize()

############################################################
# CURVED WING
############################################################
# Leading Edge points

R0_LE = 0.2926
R0_TE = 0.2926

phi_LE = Ly/R0_LE
phi_TE = Ly/R0_TE

p0_LE = gmsh.model.geo.addPoint(0, 0, R0_LE, 0)
p0_TE = gmsh.model.geo.addPoint(Lx, 0, R0_TE, 0)

p1 = gmsh.model.geo.addPoint(0, 0, 0, 0)
p2 = gmsh.model.geo.addPoint(Lx, 0, 0, 0)
p3 = gmsh.model.geo.addPoint(Ly*np.tan(sweep)+Lx, R0_TE*np.sin(phi_TE), R0_TE*(1-np.cos(phi_TE)), 0)
p4 = gmsh.model.geo.addPoint(Ly*np.tan(sweep),  R0_LE*np.sin(phi_LE), R0_LE*(1-np.cos(phi_LE)), 0)


C1 = gmsh.model.geo.add_circle_arc(p1, p0_LE, p4, tag = 1)
C2 = gmsh.model.geo.add_line(p4, p3, tag = 2)
C3 = gmsh.model.geo.add_circle_arc(p3, p0_TE, p2, tag = 3)
C4 = gmsh.model.geo.add_line(p2, p1, tag = 4)

gmsh.model.geo.add_curve_loop([C1, C2, C3, C4], tag = 1)
S1 = gmsh.model.geo.addSurfaceFilling([1])

gmsh.model.geo.synchronize()

# === Mesh
gmsh.model.mesh.setTransfiniteSurface(S1)
gmsh.model.mesh.setTransfiniteCurve(C1, Ny + 1)
gmsh.model.mesh.setTransfiniteCurve(C2, Nx + 1)
gmsh.model.mesh.setTransfiniteCurve(C3, Ny + 1)
gmsh.model.mesh.setTransfiniteCurve(C4, Nx + 1)
gmsh.model.mesh.setRecombine(2, S1)  # mesh quadrangolare

gmsh.model.mesh.generate(3)

gmsh.model.geo.synchronize()

node_tags, node_coords, _ = gmsh.model.mesh.getNodes()
nodes = {}
elem_types, elem_tags, elem_node_tags = gmsh.model.mesh.getElements(dim=2)


# renumbering of elements
gmsh.model.mesh.renumberElements(elem_tags[0],[i+1 for i in range(0,len(elem_tags[0]))])
elem_types, elem_tags, elem_node_tags = gmsh.model.mesh.getElements(dim=2)


## FLT SETUP
k_freq = np.linspace(0.001,5,20)
Mach = np.zeros_like(k_freq) + M
MK = np.empty(40)
MK[0::2] = Mach
MK[1::2] = k_freq
MK = MK.reshape(5, 8)



# OUTPUT
cwd = os.getcwd()
filepath = cwd+"/"+filename


## OTHER SETTINGS
run = True
plot = True
save_mesh = False
# result type
hdf5 = False
xdb = False
op2 = True

if save_mesh: gmsh.write(filename+".msh")

print()
print("#######################################")
print("STARTING JOB: ",filename)
print("NASTRAN DOF: ", Nx*(Ny+1)*6)
print("#######################################")
print()

with open(filename+".bdf", "w") as f:
    # === Intestazione ===
    f.write("$ MSC.Nastran input file generated by script\n")
    f.write("SOL {:d}\n".format(sol))
    f.write("CEND\n")
    
    ## Direct text input section
    if sol == 103:
        f.write("TITLE = Modal analysis of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   METHOD = 1\n")
        f.write("   SPC = 2\n")
        f.write("   VECTOR(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")
    elif sol == 144:
        f.write("DIVERG = 50\n")
        f.write("CMETHOD = 50\n")
        f.write("TITLE = SSA of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("AECONFIG = AeroSG2D\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   SPC = 2\n")
        f.write("   DISPLACEMENT(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")
        f.write("   STRESS(SORT1,REAL,VONMISES,BILIN)=ALL\n")
        f.write("TRIM = 1\n")
        f.write("AESYMXZ = Symmetric\n")
        f.write("AESYMXY = Asymmetric\n")
        f.write("AEROF = ALL\n")
        f.write("APRES = ALL\n")
    elif sol == 145:
        f.write("TITLE = Flutter analysis of composite panel\n")
        f.write("ECHO = NONE\n")
        f.write("AECONFIG = AeroSG2D\n")
        f.write("SUBCASE 1\n")
        f.write("   SUBTITLE = Default\n")
        f.write("   METHOD = 1\n")
        f.write("   SPC = 2\n")
        f.write("   VECTOR(SORT1,REAL)=ALL\n")
        f.write("   SPCFORCES(SORT1,REAL)=ALL\n")
        f.write("FMETHOD = 1\n")
        f.write("AESYMXZ = Symmetric\n")
        f.write("AESYMXY = Asymmetric\n")


    f.write("BEGIN BULK\n")

    # Parametri
    if hdf5:
        f.write("HDF5OUT PRCISION 32     CMPRMTHD LZ4     LEVEL   5\n")
    elif xdb:
        f.write("PARAM    POST      0\n")
    elif op2:
        f.write("PARAM    POST      1\n")

        
    f.write("PARAM   PRTMAXIM YES\n")
    if sol == 103 or sol == 145:
        f.write("EIGRL    1                       10      0\n")
    elif sol == 144 or sol ==145:
        f.write("PARAM    WTMASS 1.\n")
        f.write("PARAM    SNORM  20.\n")


    # === PSHEL ===

    t_formatted = "{:.7e}".format(params["t"]).replace("e-0", "-").replace("e+0", "+").replace("e-","-").replace("e+","+")
    f.write(f"PSHELL,1,1,{t_formatted},1,,1")
    f.write("\n")
    
    
    for i, tag in enumerate(node_tags):
        x = node_coords[3*i]
        y = node_coords[3*i + 1]
        z = node_coords[3*i + 2]
        f.write("GRID,{:d},,{:<8.5f},{:<8.5f},{:<8.5f}\n".format(tag, x, y, z))
        nodes[tag] = (x, y, z)
    
    # === Elementi ===

    for etype, etags, enodes in zip(elem_types, elem_tags, elem_node_tags):
        if gmsh.model.mesh.getElementProperties(etype)[0] == "Quadrilateral 4":
            for eid, i in enumerate(range(0, len(enodes), 4)):
                n1, n2, n3, n4 = enodes[i:i+4]
                pid = 1
                f.write("CQUAD4,{:d},{:d},{:d},{:d},{:d},{:d},0\n".format(
                    etags[eid], pid, n1, n2, n3, n4))
        else:
            raise Exception("Check element type.")

    
    # === MAterial ===
    line = "MAT1,1,"
    for val in props:
        if isinstance(val, float) and abs(val) >= 1e6:
            base, exp = "{:.3e}".format(val).split("e")
            base = base.rstrip("0").rstrip(".")
            if "." not in base:
                base += "."  # forza il punto decimale
            exp_sign = "+" if int(exp) >= 0 else "-"
            exp_val = str(int(exp)).lstrip("-+0")
            if exp_val == "":
                exp_val = "0"
            formatted = "{}{}{}".format(base, exp_sign, exp_val)
        else:
            formatted = str(val)
            if "." not in formatted:
                formatted += "."

        line += f"{formatted},"

    f.write(line.strip() + "\n")

    # === LOAD CASE ====
    f.write("SPCADD   2       1\n")
    # === Vincoli ===
    spc_id = 1
    tol=1e-6
    if side_to_fix  == "left":
        fixed_nodes = [nid for nid, (x, y, z) in nodes.items() if abs(x - 0.0) < tol]
    elif side_to_fix  == "right":
        fixed_nodes = [nid for nid, (x, y, z) in nodes.items() if abs(x - Lx) < tol]
    elif side_to_fix  == "bottom":
        fixed_nodes = [nid for nid, (x, y, z) in nodes.items() if abs(y - 0.0) < tol]
    elif side_to_fix  == "top":
        fixed_nodes = [nid for nid, (x, y, z) in nodes.items() if abs(y - Ly) < tol]
    else:
        fixed_nodes = []

    for nid in fixed_nodes:
        f.write("SPC     {:<8d} {:<8d} 123456\n".format(spc_id, nid))

    # AEROELASTICITY

    if sol == 144 or sol == 145:
        f.write("PARAM   AUNITS  1.\n")
        
        # aerodynamics
        f.write("AERO,0,1.,{:.4f},{:.4f}\n".format(Lx, rho_f))
        f.write("AEROS,0,0,{:.4f},{:.4f},{:.4f}\n".format(Lx,Ly*2,Lx*Ly))

        aero_id_0 = 100001
        start_id = 100001

        for j in range(0,Ny):
            
            idx1 = 4*j*Nx
            xyz1, *_ = gmsh.model.mesh.getNode(elem_node_tags[0][idx1])
            x1, y1, z1 = xyz1
            
            idx2 = 4*Nx*(j+1)-1
            xyz2, *_ = gmsh.model.mesh.getNode(elem_node_tags[0][idx2])
            x2, y2, z2 = xyz2
            
            idx3 =  4*Nx*(j+1)-2
            xyz3, *_ = gmsh.model.mesh.getNode(elem_node_tags[0][idx3])
            x3, y3, z3 = xyz3
            
            idx4 = 4*j*Nx+1
            xyz4, *_ = gmsh.model.mesh.getNode(elem_node_tags[0][idx4])
            x4, y4, z4 = xyz4
            

            
            x12 = x2 - x1  # corda root
            x43 = x3 - x4  # corda tip
            f.write("$\n")
            f.write(f"$ Surf{j+1}\n")
            f.write("$\n")
            f.write("PAERO1  {:d}\n".format(start_id))
            f.write("CAERO1,{:d},{:d},0,{:d},{:d},,,1\n".format(start_id,start_id,1,Nx))
            f.write(",{:.4f},{:.4f},{:.4f},{:.4f},{:.4f},{:.4f},{:.4f},{:.4f}\n".format(x1, y1, z1, x12, x4, y4, z4, x43))
            start_id+=Nx
        
        f.write("SPLINE4,1,100001,1,,1,,IPS,BOTH\n")
        element_ids = list(range(aero_id_0, aero_id_0 + Nelems))
        f.write("AELIST,1")
        line = "," + ",".join(str(eid) for eid in element_ids[:7]) + "\n"
        f.write(line)

        for i in range(7, len(element_ids), 8):
            line = "," + ",".join(str(eid) for eid in element_ids[i:i+8]) + "\n"
            f.write(line)
        
        set1_ids = list(range(1, (Nx+1)*(Ny+1) + 1))
        f.write("SET1,1")
        line = "," + ",".join(str(eid) for eid in set1_ids[:7]) + "\n"
        f.write(line)

        for i in range(7, len(set1_ids), 8):
            line = "," + ",".join(str(eid) for eid in set1_ids[i:i+8]) + "\n"
            f.write(line)
    
    if sol == 144:
        f.write("AESTAT  1       ANGLEA\n")
        f.write("AESTAT  2       SIDES\n")
        f.write("AESTAT  3       ROLL\n")
        f.write("AESTAT  4       PITCH\n")
        f.write("AESTAT  5       YAW\n")
        f.write("AESTAT  6       URDD1\n")
        f.write("AESTAT  7       URDD2\n")
        f.write("AESTAT  8       URDD3\n")
        f.write("AESTAT  9       URDD4\n")
        f.write("AESTAT  10      URDD5\n")
        f.write("AESTAT  11      URDD6\n")
        
        f.write("TRIM,1,{:.1f},{:.4f},ANGLEA,{:.7f},SIDES,0.\n".format(M,q,np.deg2rad(alpha)))
        f.write(",ROLL,0.,PITCH,0.,YAW,0.,URDD1,0.\n")
        f.write(",URDD2,0.,URDD3,0.,URDD4,0.,URDD5,0.\n")
        f.write(",URDD6,0.\n")
        
        
        f.write("DIVERG,50,{:d},0.0\n".format(Nroots))
        f.write("EIGC,50,CLAN,MAX,,,,{:d}\n".format(Nroots))
    
    elif sol == 145:


        for row in MK:
            row_str = ",".join(f"{x:.6f}" for x in row)
            f.write(f"MKAERO2,{row_str}\n")





        f.write("FLFACT  1       1.\n")
        f.write("FLFACT  2       0.0\n")
        
        f.write("FLFACT,3")
        line = "," + ",".join(str(eid) for eid in V_range[:7]) + "\n"
        f.write(line)
        for i in range(7, len(V_range), 8):
            line = "," + ",".join(str(eid) for eid in V_range[i:i+8]) + "\n"
            f.write(line)

        f.write("FLUTTER 1       PK      1       2       3                       .001\n")

    f.write("ENDDATA\n")

gmsh.finalize()
print(f"File scritto: {filename}.bdf")

## RUN NASTRAN

if run:
    print("Running NASTRAN win SOL {:d}".format(sol))
    if os.name == 'nt':
        command = "C:\Program Files\MSC.Software\MSC_Nastran\\2024.1\\bin\\nastran "+filename+".bdf scr=yes old=no"
    elif os.name == 'posix':
            command = "nast20234 "+filename+".bdf scr=yes old=no"

    else:
        print(os.name," platform not recognized")
        
    result = subprocess.run(command, capture_output=True, text=True, shell=True)
    print(result.stdout)

## PLOT RESULTS

if (plot):
    if sol == 103:
        res = utilities.print_vib(filename)
        print(f"{'Modo':>4} | {'lam':>12} | {'rad/s':>12} | {'Hz':>10}")
        print("-" * 47)
        for i, (lam, s, h) in enumerate(res, start=1):
            print(f"{i:4} | {lam:12.4e} | {s:12.4f} | {h:10.4f}")
    elif sol == 144:
        q_dyna = utilities.print_div(filename)
        v = np.sqrt(2*q_dyna/rho_f)
        print("Divergence velocities:\n",v)
    elif (sol == 145):
        utilities.plot_nast(filename)